version: '3.4'
services:
  database:
    image: avantpro/black-database
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      SCHEDULE: '*/5 * * * *'     # optional
      BACKUP_KEEP: 7     # optional
      RUN_ON_STARTUP: 'true' # optional
      AWS_S3_REGION: 'region'
      AWS_S3_ACCESS_KEY_ID: 'key'
      AWS_S3_SECRET_ACCESS_KEY: 'secret'
      AWS_S3_BUCKET: 'my-bucket'
      AWS_S3_PREFIX: 'backup'
      POSTGRES_HOST: 'postgres'
      POSTGRES_DATABASE: 'dbname'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'