name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: yarn install

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn release

  builddocker:
    name: BuildDocker
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate sha
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=${SHA}" >> $GITHUB_OUTPUT

      - name: Build docker image
        run: docker build -t carloslauriano/postgres-backu-s3:${{ steps.generate_sha.outputs.sha }} .

      - name: Log into the container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: |
          docker push carloslauriano/postgres-backu-s3:${{ steps.generate_sha.outputs.sha }}
          docker tag carloslauriano/postgres-backu-s3:${{ steps.generate_sha.outputs.sha }} carloslauriano/postgres-backu-s3:latest
          docker push carloslauriano/postgres-backu-s3:latest

  sincronizacao:
    name: Sincronização
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Merge main -> develop
        uses: devmasx/merge-branch@action-logs
        with:
          type: now
          from_branch: main
          target_branch: develop
          github_token: ${{ github.token }}
