name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: read # for checkout

jobs:

  sincronizacao:
    name: Sincronização
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Merge main -> develop
        uses: devmasx/merge-branch@action-logs
        with:
          type: now
          from_branch: main
          target_branch: develop
          github_token: ${{ github.token }}
